<?php

/** Auto-generated by Craftable PRO */

namespace App\Models;

use Brackets\CraftablePro\Media\AutoProcessMediaTrait;
use Brackets\CraftablePro\Media\HasMediaPreviewsTrait;
use Brackets\CraftablePro\Media\InteractsWithMedia;
use Brackets\CraftablePro\Media\ProcessMediaTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Instructor extends Model implements HasMedia
{
    use AutoProcessMediaTrait;
    use HasFactory;
    use HasMediaPreviewsTrait;
    use HasSlug;
    use InteractsWithMedia;
    use ProcessMediaTrait;

    protected $table = 'instructors';

    protected $fillable = ['first_name', 'last_name', 'slug', 'description', 'position', 'instagram_link', 'telegram_link', 'custom_link'];

    public function courses()
    {
        return $this->belongsToMany(\App\Models\Course::class);
    }

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('profile_picture')
            ->acceptsMimeTypes(['image/png', 'image/jpeg', 'image/jpg'])
            ->useFallbackUrl('favicon.png')
            ->useFallbackPath(public_path('favicon.png'));

    }

    public function registerMediaConversions(?Media $media = null): void
    {
        $this->autoRegisterPreviews();
    }

    public function getProfilePictureUrlAttribute(): string
    {
        return $this->getFirstMediaUrl('profile_picture');
    }

    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom(['first_name', 'last_name'])
            ->saveSlugsTo('slug');
    }

    protected $casts = [];
}
